source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"
gem "rails", "7.0.7"
gem "sprockets-rails"
gem "mysql2"
gem "puma"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "bcrypt"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem "sassc-rails"
gem "aws-sdk-s3", require: false
gem "image_processing"
gem 'mini_magick'
gem 'active_storage_validations'
gem 'rack-cors'
gem 'streamio-ffmpeg'
gem 'openssl'
gem 'sidekiq'
gem "redis"
gem 'redis-session-store'
# gem "kredis"
gem 'mime-types'
gem "meilisearch-rails"
gem 'mecab'
gem 'natto'
gem 'chunky_png'
gem 'rubyzip', '2.3.0'
gem 'rails-i18n'
group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end
group :development do
  gem "web-console"
  # gem "rack-mini-profiler"
  # gem "spring"
end
group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
